# Generated by Django 4.0.5 on 2022-06-25 10:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_rename_skills_skill_project_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Profile',
        ),
    ]
