# Generated by Django 4.0.5 on 2022-07-01 09:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_project_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillFrom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('desception', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
